package me.superkoh.evpn.domain.model.evpn;

import java.util.Date;

public class Banner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.id
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.asset_url
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    private String assetUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.link_url
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    private String linkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.online_time
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    private Date onlineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.offline_time
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    private Date offlineTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.id
     *
     * @return the value of banner.id
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.id
     *
     * @param id the value for banner.id
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.asset_url
     *
     * @return the value of banner.asset_url
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    public String getAssetUrl() {
        return assetUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.asset_url
     *
     * @param assetUrl the value for banner.asset_url
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    public void setAssetUrl(String assetUrl) {
        this.assetUrl = assetUrl == null ? null : assetUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.link_url
     *
     * @return the value of banner.link_url
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.link_url
     *
     * @param linkUrl the value for banner.link_url
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.online_time
     *
     * @return the value of banner.online_time
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    public Date getOnlineTime() {
        return onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.online_time
     *
     * @param onlineTime the value for banner.online_time
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    public void setOnlineTime(Date onlineTime) {
        this.onlineTime = onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.offline_time
     *
     * @return the value of banner.offline_time
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    public Date getOfflineTime() {
        return offlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.offline_time
     *
     * @param offlineTime the value for banner.offline_time
     *
     * @mbggenerated Tue May 10 00:10:31 CST 2016
     */
    public void setOfflineTime(Date offlineTime) {
        this.offlineTime = offlineTime;
    }
}