package me.superkoh.evpn.domain.model.evpn;

import me.superkoh.evpn.domain.base.BaseRecord;

import java.util.Date;

public class MobileValidationCode extends BaseRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_validation_code.id
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_validation_code.mobile
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_validation_code.code
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_validation_code.expire_time
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    private Date expireTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_validation_code.id
     *
     * @return the value of mobile_validation_code.id
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_validation_code.id
     *
     * @param id the value for mobile_validation_code.id
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_validation_code.mobile
     *
     * @return the value of mobile_validation_code.mobile
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_validation_code.mobile
     *
     * @param mobile the value for mobile_validation_code.mobile
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_validation_code.code
     *
     * @return the value of mobile_validation_code.code
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_validation_code.code
     *
     * @param code the value for mobile_validation_code.code
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_validation_code.expire_time
     *
     * @return the value of mobile_validation_code.expire_time
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_validation_code.expire_time
     *
     * @param expireTime the value for mobile_validation_code.expire_time
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }
}