package me.superkoh.evpn.domain.model.evpn;

import me.superkoh.evpn.domain.base.BaseRecord;

public class Order extends BaseRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.total_price
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    private Integer totalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.deliver
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    private Integer deliver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.status
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.content
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.total_price
     *
     * @return the value of order_info.total_price
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    public Integer getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.total_price
     *
     * @param totalPrice the value for order_info.total_price
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.deliver
     *
     * @return the value of order_info.deliver
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    public Integer getDeliver() {
        return deliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.deliver
     *
     * @param deliver the value for order_info.deliver
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    public void setDeliver(Integer deliver) {
        this.deliver = deliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.status
     *
     * @return the value of order_info.status
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.status
     *
     * @param status the value for order_info.status
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.content
     *
     * @return the value of order_info.content
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.content
     *
     * @param content the value for order_info.content
     *
     * @mbggenerated Mon May 23 12:01:53 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}