package me.superkoh.evpn.domain.model.evpn;

import me.superkoh.evpn.domain.base.BaseRecord;

public class Order extends BaseRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Fri May 20 15:54:07 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.deliver
     *
     * @mbggenerated Fri May 20 15:54:07 CST 2016
     */
    private Integer deliver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.content
     *
     * @mbggenerated Fri May 20 15:54:07 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Fri May 20 15:54:07 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Fri May 20 15:54:07 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.deliver
     *
     * @return the value of order.deliver
     *
     * @mbggenerated Fri May 20 15:54:07 CST 2016
     */
    public Integer getDeliver() {
        return deliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.deliver
     *
     * @param deliver the value for order.deliver
     *
     * @mbggenerated Fri May 20 15:54:07 CST 2016
     */
    public void setDeliver(Integer deliver) {
        this.deliver = deliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.content
     *
     * @return the value of order.content
     *
     * @mbggenerated Fri May 20 15:54:07 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.content
     *
     * @param content the value for order.content
     *
     * @mbggenerated Fri May 20 15:54:07 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}