package me.superkoh.evpn.domain.model.evpn;

import java.util.Date;
import me.superkoh.evpn.domain.base.BaseRecord;

public class VipUserToken extends BaseRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_user_token.vip_user_id
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    private Integer vipUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_user_token.token
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_user_token.create_time
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_user_token.vip_user_id
     *
     * @return the value of vip_user_token.vip_user_id
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public Integer getVipUserId() {
        return vipUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_user_token.vip_user_id
     *
     * @param vipUserId the value for vip_user_token.vip_user_id
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public void setVipUserId(Integer vipUserId) {
        this.vipUserId = vipUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_user_token.token
     *
     * @return the value of vip_user_token.token
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_user_token.token
     *
     * @param token the value for vip_user_token.token
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_user_token.create_time
     *
     * @return the value of vip_user_token.create_time
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_user_token.create_time
     *
     * @param createTime the value for vip_user_token.create_time
     *
     * @mbggenerated Tue May 17 17:59:00 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}