package me.superkoh.evpn.domain.model;

import java.util.Date;

public class EVpnUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evpn_user.id
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evpn_user.username
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evpn_user.monthly_traffic
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    private Long monthlyTraffic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evpn_user.award_traffic
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    private Long awardTraffic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evpn_user.award_end_date
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    private Date awardEndDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evpn_user.id
     *
     * @return the value of evpn_user.id
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evpn_user.id
     *
     * @param id the value for evpn_user.id
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evpn_user.username
     *
     * @return the value of evpn_user.username
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evpn_user.username
     *
     * @param username the value for evpn_user.username
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evpn_user.monthly_traffic
     *
     * @return the value of evpn_user.monthly_traffic
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public Long getMonthlyTraffic() {
        return monthlyTraffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evpn_user.monthly_traffic
     *
     * @param monthlyTraffic the value for evpn_user.monthly_traffic
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public void setMonthlyTraffic(Long monthlyTraffic) {
        this.monthlyTraffic = monthlyTraffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evpn_user.award_traffic
     *
     * @return the value of evpn_user.award_traffic
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public Long getAwardTraffic() {
        return awardTraffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evpn_user.award_traffic
     *
     * @param awardTraffic the value for evpn_user.award_traffic
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public void setAwardTraffic(Long awardTraffic) {
        this.awardTraffic = awardTraffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evpn_user.award_end_date
     *
     * @return the value of evpn_user.award_end_date
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public Date getAwardEndDate() {
        return awardEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evpn_user.award_end_date
     *
     * @param awardEndDate the value for evpn_user.award_end_date
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public void setAwardEndDate(Date awardEndDate) {
        this.awardEndDate = awardEndDate;
    }
}