package me.superkoh.evpn.domain.model;

public class EVpnInviteCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evpn_invite_code.id
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evpn_invite_code.username
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evpn_invite_code.code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column evpn_invite_code.used_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    private String usedUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evpn_invite_code.id
     *
     * @return the value of evpn_invite_code.id
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evpn_invite_code.id
     *
     * @param id the value for evpn_invite_code.id
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evpn_invite_code.username
     *
     * @return the value of evpn_invite_code.username
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evpn_invite_code.username
     *
     * @param username the value for evpn_invite_code.username
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evpn_invite_code.code
     *
     * @return the value of evpn_invite_code.code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evpn_invite_code.code
     *
     * @param code the value for evpn_invite_code.code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column evpn_invite_code.used_user
     *
     * @return the value of evpn_invite_code.used_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public String getUsedUser() {
        return usedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column evpn_invite_code.used_user
     *
     * @param usedUser the value for evpn_invite_code.used_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public void setUsedUser(String usedUser) {
        this.usedUser = usedUser == null ? null : usedUser.trim();
    }
}