package me.superkoh.evpn.domain.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EVpnUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public EVpnUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andMonthlyTrafficIsNull() {
            addCriterion("monthly_traffic is null");
            return (Criteria) this;
        }

        public Criteria andMonthlyTrafficIsNotNull() {
            addCriterion("monthly_traffic is not null");
            return (Criteria) this;
        }

        public Criteria andMonthlyTrafficEqualTo(Long value) {
            addCriterion("monthly_traffic =", value, "monthlyTraffic");
            return (Criteria) this;
        }

        public Criteria andMonthlyTrafficNotEqualTo(Long value) {
            addCriterion("monthly_traffic <>", value, "monthlyTraffic");
            return (Criteria) this;
        }

        public Criteria andMonthlyTrafficGreaterThan(Long value) {
            addCriterion("monthly_traffic >", value, "monthlyTraffic");
            return (Criteria) this;
        }

        public Criteria andMonthlyTrafficGreaterThanOrEqualTo(Long value) {
            addCriterion("monthly_traffic >=", value, "monthlyTraffic");
            return (Criteria) this;
        }

        public Criteria andMonthlyTrafficLessThan(Long value) {
            addCriterion("monthly_traffic <", value, "monthlyTraffic");
            return (Criteria) this;
        }

        public Criteria andMonthlyTrafficLessThanOrEqualTo(Long value) {
            addCriterion("monthly_traffic <=", value, "monthlyTraffic");
            return (Criteria) this;
        }

        public Criteria andMonthlyTrafficIn(List<Long> values) {
            addCriterion("monthly_traffic in", values, "monthlyTraffic");
            return (Criteria) this;
        }

        public Criteria andMonthlyTrafficNotIn(List<Long> values) {
            addCriterion("monthly_traffic not in", values, "monthlyTraffic");
            return (Criteria) this;
        }

        public Criteria andMonthlyTrafficBetween(Long value1, Long value2) {
            addCriterion("monthly_traffic between", value1, value2, "monthlyTraffic");
            return (Criteria) this;
        }

        public Criteria andMonthlyTrafficNotBetween(Long value1, Long value2) {
            addCriterion("monthly_traffic not between", value1, value2, "monthlyTraffic");
            return (Criteria) this;
        }

        public Criteria andAwardTrafficIsNull() {
            addCriterion("award_traffic is null");
            return (Criteria) this;
        }

        public Criteria andAwardTrafficIsNotNull() {
            addCriterion("award_traffic is not null");
            return (Criteria) this;
        }

        public Criteria andAwardTrafficEqualTo(Long value) {
            addCriterion("award_traffic =", value, "awardTraffic");
            return (Criteria) this;
        }

        public Criteria andAwardTrafficNotEqualTo(Long value) {
            addCriterion("award_traffic <>", value, "awardTraffic");
            return (Criteria) this;
        }

        public Criteria andAwardTrafficGreaterThan(Long value) {
            addCriterion("award_traffic >", value, "awardTraffic");
            return (Criteria) this;
        }

        public Criteria andAwardTrafficGreaterThanOrEqualTo(Long value) {
            addCriterion("award_traffic >=", value, "awardTraffic");
            return (Criteria) this;
        }

        public Criteria andAwardTrafficLessThan(Long value) {
            addCriterion("award_traffic <", value, "awardTraffic");
            return (Criteria) this;
        }

        public Criteria andAwardTrafficLessThanOrEqualTo(Long value) {
            addCriterion("award_traffic <=", value, "awardTraffic");
            return (Criteria) this;
        }

        public Criteria andAwardTrafficIn(List<Long> values) {
            addCriterion("award_traffic in", values, "awardTraffic");
            return (Criteria) this;
        }

        public Criteria andAwardTrafficNotIn(List<Long> values) {
            addCriterion("award_traffic not in", values, "awardTraffic");
            return (Criteria) this;
        }

        public Criteria andAwardTrafficBetween(Long value1, Long value2) {
            addCriterion("award_traffic between", value1, value2, "awardTraffic");
            return (Criteria) this;
        }

        public Criteria andAwardTrafficNotBetween(Long value1, Long value2) {
            addCriterion("award_traffic not between", value1, value2, "awardTraffic");
            return (Criteria) this;
        }

        public Criteria andAwardEndDateIsNull() {
            addCriterion("award_end_date is null");
            return (Criteria) this;
        }

        public Criteria andAwardEndDateIsNotNull() {
            addCriterion("award_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andAwardEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("award_end_date =", value, "awardEndDate");
            return (Criteria) this;
        }

        public Criteria andAwardEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("award_end_date <>", value, "awardEndDate");
            return (Criteria) this;
        }

        public Criteria andAwardEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("award_end_date >", value, "awardEndDate");
            return (Criteria) this;
        }

        public Criteria andAwardEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("award_end_date >=", value, "awardEndDate");
            return (Criteria) this;
        }

        public Criteria andAwardEndDateLessThan(Date value) {
            addCriterionForJDBCDate("award_end_date <", value, "awardEndDate");
            return (Criteria) this;
        }

        public Criteria andAwardEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("award_end_date <=", value, "awardEndDate");
            return (Criteria) this;
        }

        public Criteria andAwardEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("award_end_date in", values, "awardEndDate");
            return (Criteria) this;
        }

        public Criteria andAwardEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("award_end_date not in", values, "awardEndDate");
            return (Criteria) this;
        }

        public Criteria andAwardEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("award_end_date between", value1, value2, "awardEndDate");
            return (Criteria) this;
        }

        public Criteria andAwardEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("award_end_date not between", value1, value2, "awardEndDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table evpn_user
     *
     * @mbggenerated do_not_delete_during_merge Thu Apr 21 22:44:30 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}