package me.superkoh.evpn.domain.model;

public class Nas {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nas.id
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nas.nasname
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String nasname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nas.shortname
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nas.type
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nas.ports
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private Integer ports;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nas.secret
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String secret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nas.server
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String server;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nas.community
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String community;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nas.description
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nas.id
     *
     * @return the value of nas.id
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nas.id
     *
     * @param id the value for nas.id
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nas.nasname
     *
     * @return the value of nas.nasname
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getNasname() {
        return nasname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nas.nasname
     *
     * @param nasname the value for nas.nasname
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setNasname(String nasname) {
        this.nasname = nasname == null ? null : nasname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nas.shortname
     *
     * @return the value of nas.shortname
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nas.shortname
     *
     * @param shortname the value for nas.shortname
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nas.type
     *
     * @return the value of nas.type
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nas.type
     *
     * @param type the value for nas.type
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nas.ports
     *
     * @return the value of nas.ports
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Integer getPorts() {
        return ports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nas.ports
     *
     * @param ports the value for nas.ports
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setPorts(Integer ports) {
        this.ports = ports;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nas.secret
     *
     * @return the value of nas.secret
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nas.secret
     *
     * @param secret the value for nas.secret
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setSecret(String secret) {
        this.secret = secret == null ? null : secret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nas.server
     *
     * @return the value of nas.server
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getServer() {
        return server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nas.server
     *
     * @param server the value for nas.server
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setServer(String server) {
        this.server = server == null ? null : server.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nas.community
     *
     * @return the value of nas.community
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getCommunity() {
        return community;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nas.community
     *
     * @param community the value for nas.community
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setCommunity(String community) {
        this.community = community == null ? null : community.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nas.description
     *
     * @return the value of nas.description
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nas.description
     *
     * @param description the value for nas.description
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}