package me.superkoh.evpn.domain.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RadAcctExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public RadAcctExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRadacctidIsNull() {
            addCriterion("radacctid is null");
            return (Criteria) this;
        }

        public Criteria andRadacctidIsNotNull() {
            addCriterion("radacctid is not null");
            return (Criteria) this;
        }

        public Criteria andRadacctidEqualTo(Long value) {
            addCriterion("radacctid =", value, "radacctid");
            return (Criteria) this;
        }

        public Criteria andRadacctidNotEqualTo(Long value) {
            addCriterion("radacctid <>", value, "radacctid");
            return (Criteria) this;
        }

        public Criteria andRadacctidGreaterThan(Long value) {
            addCriterion("radacctid >", value, "radacctid");
            return (Criteria) this;
        }

        public Criteria andRadacctidGreaterThanOrEqualTo(Long value) {
            addCriterion("radacctid >=", value, "radacctid");
            return (Criteria) this;
        }

        public Criteria andRadacctidLessThan(Long value) {
            addCriterion("radacctid <", value, "radacctid");
            return (Criteria) this;
        }

        public Criteria andRadacctidLessThanOrEqualTo(Long value) {
            addCriterion("radacctid <=", value, "radacctid");
            return (Criteria) this;
        }

        public Criteria andRadacctidIn(List<Long> values) {
            addCriterion("radacctid in", values, "radacctid");
            return (Criteria) this;
        }

        public Criteria andRadacctidNotIn(List<Long> values) {
            addCriterion("radacctid not in", values, "radacctid");
            return (Criteria) this;
        }

        public Criteria andRadacctidBetween(Long value1, Long value2) {
            addCriterion("radacctid between", value1, value2, "radacctid");
            return (Criteria) this;
        }

        public Criteria andRadacctidNotBetween(Long value1, Long value2) {
            addCriterion("radacctid not between", value1, value2, "radacctid");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidIsNull() {
            addCriterion("acctsessionid is null");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidIsNotNull() {
            addCriterion("acctsessionid is not null");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidEqualTo(String value) {
            addCriterion("acctsessionid =", value, "acctsessionid");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidNotEqualTo(String value) {
            addCriterion("acctsessionid <>", value, "acctsessionid");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidGreaterThan(String value) {
            addCriterion("acctsessionid >", value, "acctsessionid");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidGreaterThanOrEqualTo(String value) {
            addCriterion("acctsessionid >=", value, "acctsessionid");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidLessThan(String value) {
            addCriterion("acctsessionid <", value, "acctsessionid");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidLessThanOrEqualTo(String value) {
            addCriterion("acctsessionid <=", value, "acctsessionid");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidLike(String value) {
            addCriterion("acctsessionid like", value, "acctsessionid");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidNotLike(String value) {
            addCriterion("acctsessionid not like", value, "acctsessionid");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidIn(List<String> values) {
            addCriterion("acctsessionid in", values, "acctsessionid");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidNotIn(List<String> values) {
            addCriterion("acctsessionid not in", values, "acctsessionid");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidBetween(String value1, String value2) {
            addCriterion("acctsessionid between", value1, value2, "acctsessionid");
            return (Criteria) this;
        }

        public Criteria andAcctsessionidNotBetween(String value1, String value2) {
            addCriterion("acctsessionid not between", value1, value2, "acctsessionid");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidIsNull() {
            addCriterion("acctuniqueid is null");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidIsNotNull() {
            addCriterion("acctuniqueid is not null");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidEqualTo(String value) {
            addCriterion("acctuniqueid =", value, "acctuniqueid");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidNotEqualTo(String value) {
            addCriterion("acctuniqueid <>", value, "acctuniqueid");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidGreaterThan(String value) {
            addCriterion("acctuniqueid >", value, "acctuniqueid");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidGreaterThanOrEqualTo(String value) {
            addCriterion("acctuniqueid >=", value, "acctuniqueid");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidLessThan(String value) {
            addCriterion("acctuniqueid <", value, "acctuniqueid");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidLessThanOrEqualTo(String value) {
            addCriterion("acctuniqueid <=", value, "acctuniqueid");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidLike(String value) {
            addCriterion("acctuniqueid like", value, "acctuniqueid");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidNotLike(String value) {
            addCriterion("acctuniqueid not like", value, "acctuniqueid");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidIn(List<String> values) {
            addCriterion("acctuniqueid in", values, "acctuniqueid");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidNotIn(List<String> values) {
            addCriterion("acctuniqueid not in", values, "acctuniqueid");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidBetween(String value1, String value2) {
            addCriterion("acctuniqueid between", value1, value2, "acctuniqueid");
            return (Criteria) this;
        }

        public Criteria andAcctuniqueidNotBetween(String value1, String value2) {
            addCriterion("acctuniqueid not between", value1, value2, "acctuniqueid");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andGroupnameIsNull() {
            addCriterion("groupname is null");
            return (Criteria) this;
        }

        public Criteria andGroupnameIsNotNull() {
            addCriterion("groupname is not null");
            return (Criteria) this;
        }

        public Criteria andGroupnameEqualTo(String value) {
            addCriterion("groupname =", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameNotEqualTo(String value) {
            addCriterion("groupname <>", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameGreaterThan(String value) {
            addCriterion("groupname >", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameGreaterThanOrEqualTo(String value) {
            addCriterion("groupname >=", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameLessThan(String value) {
            addCriterion("groupname <", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameLessThanOrEqualTo(String value) {
            addCriterion("groupname <=", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameLike(String value) {
            addCriterion("groupname like", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameNotLike(String value) {
            addCriterion("groupname not like", value, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameIn(List<String> values) {
            addCriterion("groupname in", values, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameNotIn(List<String> values) {
            addCriterion("groupname not in", values, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameBetween(String value1, String value2) {
            addCriterion("groupname between", value1, value2, "groupname");
            return (Criteria) this;
        }

        public Criteria andGroupnameNotBetween(String value1, String value2) {
            addCriterion("groupname not between", value1, value2, "groupname");
            return (Criteria) this;
        }

        public Criteria andRealmIsNull() {
            addCriterion("realm is null");
            return (Criteria) this;
        }

        public Criteria andRealmIsNotNull() {
            addCriterion("realm is not null");
            return (Criteria) this;
        }

        public Criteria andRealmEqualTo(String value) {
            addCriterion("realm =", value, "realm");
            return (Criteria) this;
        }

        public Criteria andRealmNotEqualTo(String value) {
            addCriterion("realm <>", value, "realm");
            return (Criteria) this;
        }

        public Criteria andRealmGreaterThan(String value) {
            addCriterion("realm >", value, "realm");
            return (Criteria) this;
        }

        public Criteria andRealmGreaterThanOrEqualTo(String value) {
            addCriterion("realm >=", value, "realm");
            return (Criteria) this;
        }

        public Criteria andRealmLessThan(String value) {
            addCriterion("realm <", value, "realm");
            return (Criteria) this;
        }

        public Criteria andRealmLessThanOrEqualTo(String value) {
            addCriterion("realm <=", value, "realm");
            return (Criteria) this;
        }

        public Criteria andRealmLike(String value) {
            addCriterion("realm like", value, "realm");
            return (Criteria) this;
        }

        public Criteria andRealmNotLike(String value) {
            addCriterion("realm not like", value, "realm");
            return (Criteria) this;
        }

        public Criteria andRealmIn(List<String> values) {
            addCriterion("realm in", values, "realm");
            return (Criteria) this;
        }

        public Criteria andRealmNotIn(List<String> values) {
            addCriterion("realm not in", values, "realm");
            return (Criteria) this;
        }

        public Criteria andRealmBetween(String value1, String value2) {
            addCriterion("realm between", value1, value2, "realm");
            return (Criteria) this;
        }

        public Criteria andRealmNotBetween(String value1, String value2) {
            addCriterion("realm not between", value1, value2, "realm");
            return (Criteria) this;
        }

        public Criteria andNasipaddressIsNull() {
            addCriterion("nasipaddress is null");
            return (Criteria) this;
        }

        public Criteria andNasipaddressIsNotNull() {
            addCriterion("nasipaddress is not null");
            return (Criteria) this;
        }

        public Criteria andNasipaddressEqualTo(String value) {
            addCriterion("nasipaddress =", value, "nasipaddress");
            return (Criteria) this;
        }

        public Criteria andNasipaddressNotEqualTo(String value) {
            addCriterion("nasipaddress <>", value, "nasipaddress");
            return (Criteria) this;
        }

        public Criteria andNasipaddressGreaterThan(String value) {
            addCriterion("nasipaddress >", value, "nasipaddress");
            return (Criteria) this;
        }

        public Criteria andNasipaddressGreaterThanOrEqualTo(String value) {
            addCriterion("nasipaddress >=", value, "nasipaddress");
            return (Criteria) this;
        }

        public Criteria andNasipaddressLessThan(String value) {
            addCriterion("nasipaddress <", value, "nasipaddress");
            return (Criteria) this;
        }

        public Criteria andNasipaddressLessThanOrEqualTo(String value) {
            addCriterion("nasipaddress <=", value, "nasipaddress");
            return (Criteria) this;
        }

        public Criteria andNasipaddressLike(String value) {
            addCriterion("nasipaddress like", value, "nasipaddress");
            return (Criteria) this;
        }

        public Criteria andNasipaddressNotLike(String value) {
            addCriterion("nasipaddress not like", value, "nasipaddress");
            return (Criteria) this;
        }

        public Criteria andNasipaddressIn(List<String> values) {
            addCriterion("nasipaddress in", values, "nasipaddress");
            return (Criteria) this;
        }

        public Criteria andNasipaddressNotIn(List<String> values) {
            addCriterion("nasipaddress not in", values, "nasipaddress");
            return (Criteria) this;
        }

        public Criteria andNasipaddressBetween(String value1, String value2) {
            addCriterion("nasipaddress between", value1, value2, "nasipaddress");
            return (Criteria) this;
        }

        public Criteria andNasipaddressNotBetween(String value1, String value2) {
            addCriterion("nasipaddress not between", value1, value2, "nasipaddress");
            return (Criteria) this;
        }

        public Criteria andNasportidIsNull() {
            addCriterion("nasportid is null");
            return (Criteria) this;
        }

        public Criteria andNasportidIsNotNull() {
            addCriterion("nasportid is not null");
            return (Criteria) this;
        }

        public Criteria andNasportidEqualTo(String value) {
            addCriterion("nasportid =", value, "nasportid");
            return (Criteria) this;
        }

        public Criteria andNasportidNotEqualTo(String value) {
            addCriterion("nasportid <>", value, "nasportid");
            return (Criteria) this;
        }

        public Criteria andNasportidGreaterThan(String value) {
            addCriterion("nasportid >", value, "nasportid");
            return (Criteria) this;
        }

        public Criteria andNasportidGreaterThanOrEqualTo(String value) {
            addCriterion("nasportid >=", value, "nasportid");
            return (Criteria) this;
        }

        public Criteria andNasportidLessThan(String value) {
            addCriterion("nasportid <", value, "nasportid");
            return (Criteria) this;
        }

        public Criteria andNasportidLessThanOrEqualTo(String value) {
            addCriterion("nasportid <=", value, "nasportid");
            return (Criteria) this;
        }

        public Criteria andNasportidLike(String value) {
            addCriterion("nasportid like", value, "nasportid");
            return (Criteria) this;
        }

        public Criteria andNasportidNotLike(String value) {
            addCriterion("nasportid not like", value, "nasportid");
            return (Criteria) this;
        }

        public Criteria andNasportidIn(List<String> values) {
            addCriterion("nasportid in", values, "nasportid");
            return (Criteria) this;
        }

        public Criteria andNasportidNotIn(List<String> values) {
            addCriterion("nasportid not in", values, "nasportid");
            return (Criteria) this;
        }

        public Criteria andNasportidBetween(String value1, String value2) {
            addCriterion("nasportid between", value1, value2, "nasportid");
            return (Criteria) this;
        }

        public Criteria andNasportidNotBetween(String value1, String value2) {
            addCriterion("nasportid not between", value1, value2, "nasportid");
            return (Criteria) this;
        }

        public Criteria andNasporttypeIsNull() {
            addCriterion("nasporttype is null");
            return (Criteria) this;
        }

        public Criteria andNasporttypeIsNotNull() {
            addCriterion("nasporttype is not null");
            return (Criteria) this;
        }

        public Criteria andNasporttypeEqualTo(String value) {
            addCriterion("nasporttype =", value, "nasporttype");
            return (Criteria) this;
        }

        public Criteria andNasporttypeNotEqualTo(String value) {
            addCriterion("nasporttype <>", value, "nasporttype");
            return (Criteria) this;
        }

        public Criteria andNasporttypeGreaterThan(String value) {
            addCriterion("nasporttype >", value, "nasporttype");
            return (Criteria) this;
        }

        public Criteria andNasporttypeGreaterThanOrEqualTo(String value) {
            addCriterion("nasporttype >=", value, "nasporttype");
            return (Criteria) this;
        }

        public Criteria andNasporttypeLessThan(String value) {
            addCriterion("nasporttype <", value, "nasporttype");
            return (Criteria) this;
        }

        public Criteria andNasporttypeLessThanOrEqualTo(String value) {
            addCriterion("nasporttype <=", value, "nasporttype");
            return (Criteria) this;
        }

        public Criteria andNasporttypeLike(String value) {
            addCriterion("nasporttype like", value, "nasporttype");
            return (Criteria) this;
        }

        public Criteria andNasporttypeNotLike(String value) {
            addCriterion("nasporttype not like", value, "nasporttype");
            return (Criteria) this;
        }

        public Criteria andNasporttypeIn(List<String> values) {
            addCriterion("nasporttype in", values, "nasporttype");
            return (Criteria) this;
        }

        public Criteria andNasporttypeNotIn(List<String> values) {
            addCriterion("nasporttype not in", values, "nasporttype");
            return (Criteria) this;
        }

        public Criteria andNasporttypeBetween(String value1, String value2) {
            addCriterion("nasporttype between", value1, value2, "nasporttype");
            return (Criteria) this;
        }

        public Criteria andNasporttypeNotBetween(String value1, String value2) {
            addCriterion("nasporttype not between", value1, value2, "nasporttype");
            return (Criteria) this;
        }

        public Criteria andAcctstarttimeIsNull() {
            addCriterion("acctstarttime is null");
            return (Criteria) this;
        }

        public Criteria andAcctstarttimeIsNotNull() {
            addCriterion("acctstarttime is not null");
            return (Criteria) this;
        }

        public Criteria andAcctstarttimeEqualTo(Date value) {
            addCriterion("acctstarttime =", value, "acctstarttime");
            return (Criteria) this;
        }

        public Criteria andAcctstarttimeNotEqualTo(Date value) {
            addCriterion("acctstarttime <>", value, "acctstarttime");
            return (Criteria) this;
        }

        public Criteria andAcctstarttimeGreaterThan(Date value) {
            addCriterion("acctstarttime >", value, "acctstarttime");
            return (Criteria) this;
        }

        public Criteria andAcctstarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("acctstarttime >=", value, "acctstarttime");
            return (Criteria) this;
        }

        public Criteria andAcctstarttimeLessThan(Date value) {
            addCriterion("acctstarttime <", value, "acctstarttime");
            return (Criteria) this;
        }

        public Criteria andAcctstarttimeLessThanOrEqualTo(Date value) {
            addCriterion("acctstarttime <=", value, "acctstarttime");
            return (Criteria) this;
        }

        public Criteria andAcctstarttimeIn(List<Date> values) {
            addCriterion("acctstarttime in", values, "acctstarttime");
            return (Criteria) this;
        }

        public Criteria andAcctstarttimeNotIn(List<Date> values) {
            addCriterion("acctstarttime not in", values, "acctstarttime");
            return (Criteria) this;
        }

        public Criteria andAcctstarttimeBetween(Date value1, Date value2) {
            addCriterion("acctstarttime between", value1, value2, "acctstarttime");
            return (Criteria) this;
        }

        public Criteria andAcctstarttimeNotBetween(Date value1, Date value2) {
            addCriterion("acctstarttime not between", value1, value2, "acctstarttime");
            return (Criteria) this;
        }

        public Criteria andAcctstoptimeIsNull() {
            addCriterion("acctstoptime is null");
            return (Criteria) this;
        }

        public Criteria andAcctstoptimeIsNotNull() {
            addCriterion("acctstoptime is not null");
            return (Criteria) this;
        }

        public Criteria andAcctstoptimeEqualTo(Date value) {
            addCriterion("acctstoptime =", value, "acctstoptime");
            return (Criteria) this;
        }

        public Criteria andAcctstoptimeNotEqualTo(Date value) {
            addCriterion("acctstoptime <>", value, "acctstoptime");
            return (Criteria) this;
        }

        public Criteria andAcctstoptimeGreaterThan(Date value) {
            addCriterion("acctstoptime >", value, "acctstoptime");
            return (Criteria) this;
        }

        public Criteria andAcctstoptimeGreaterThanOrEqualTo(Date value) {
            addCriterion("acctstoptime >=", value, "acctstoptime");
            return (Criteria) this;
        }

        public Criteria andAcctstoptimeLessThan(Date value) {
            addCriterion("acctstoptime <", value, "acctstoptime");
            return (Criteria) this;
        }

        public Criteria andAcctstoptimeLessThanOrEqualTo(Date value) {
            addCriterion("acctstoptime <=", value, "acctstoptime");
            return (Criteria) this;
        }

        public Criteria andAcctstoptimeIn(List<Date> values) {
            addCriterion("acctstoptime in", values, "acctstoptime");
            return (Criteria) this;
        }

        public Criteria andAcctstoptimeNotIn(List<Date> values) {
            addCriterion("acctstoptime not in", values, "acctstoptime");
            return (Criteria) this;
        }

        public Criteria andAcctstoptimeBetween(Date value1, Date value2) {
            addCriterion("acctstoptime between", value1, value2, "acctstoptime");
            return (Criteria) this;
        }

        public Criteria andAcctstoptimeNotBetween(Date value1, Date value2) {
            addCriterion("acctstoptime not between", value1, value2, "acctstoptime");
            return (Criteria) this;
        }

        public Criteria andAcctsessiontimeIsNull() {
            addCriterion("acctsessiontime is null");
            return (Criteria) this;
        }

        public Criteria andAcctsessiontimeIsNotNull() {
            addCriterion("acctsessiontime is not null");
            return (Criteria) this;
        }

        public Criteria andAcctsessiontimeEqualTo(Integer value) {
            addCriterion("acctsessiontime =", value, "acctsessiontime");
            return (Criteria) this;
        }

        public Criteria andAcctsessiontimeNotEqualTo(Integer value) {
            addCriterion("acctsessiontime <>", value, "acctsessiontime");
            return (Criteria) this;
        }

        public Criteria andAcctsessiontimeGreaterThan(Integer value) {
            addCriterion("acctsessiontime >", value, "acctsessiontime");
            return (Criteria) this;
        }

        public Criteria andAcctsessiontimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("acctsessiontime >=", value, "acctsessiontime");
            return (Criteria) this;
        }

        public Criteria andAcctsessiontimeLessThan(Integer value) {
            addCriterion("acctsessiontime <", value, "acctsessiontime");
            return (Criteria) this;
        }

        public Criteria andAcctsessiontimeLessThanOrEqualTo(Integer value) {
            addCriterion("acctsessiontime <=", value, "acctsessiontime");
            return (Criteria) this;
        }

        public Criteria andAcctsessiontimeIn(List<Integer> values) {
            addCriterion("acctsessiontime in", values, "acctsessiontime");
            return (Criteria) this;
        }

        public Criteria andAcctsessiontimeNotIn(List<Integer> values) {
            addCriterion("acctsessiontime not in", values, "acctsessiontime");
            return (Criteria) this;
        }

        public Criteria andAcctsessiontimeBetween(Integer value1, Integer value2) {
            addCriterion("acctsessiontime between", value1, value2, "acctsessiontime");
            return (Criteria) this;
        }

        public Criteria andAcctsessiontimeNotBetween(Integer value1, Integer value2) {
            addCriterion("acctsessiontime not between", value1, value2, "acctsessiontime");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticIsNull() {
            addCriterion("acctauthentic is null");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticIsNotNull() {
            addCriterion("acctauthentic is not null");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticEqualTo(String value) {
            addCriterion("acctauthentic =", value, "acctauthentic");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticNotEqualTo(String value) {
            addCriterion("acctauthentic <>", value, "acctauthentic");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticGreaterThan(String value) {
            addCriterion("acctauthentic >", value, "acctauthentic");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticGreaterThanOrEqualTo(String value) {
            addCriterion("acctauthentic >=", value, "acctauthentic");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticLessThan(String value) {
            addCriterion("acctauthentic <", value, "acctauthentic");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticLessThanOrEqualTo(String value) {
            addCriterion("acctauthentic <=", value, "acctauthentic");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticLike(String value) {
            addCriterion("acctauthentic like", value, "acctauthentic");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticNotLike(String value) {
            addCriterion("acctauthentic not like", value, "acctauthentic");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticIn(List<String> values) {
            addCriterion("acctauthentic in", values, "acctauthentic");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticNotIn(List<String> values) {
            addCriterion("acctauthentic not in", values, "acctauthentic");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticBetween(String value1, String value2) {
            addCriterion("acctauthentic between", value1, value2, "acctauthentic");
            return (Criteria) this;
        }

        public Criteria andAcctauthenticNotBetween(String value1, String value2) {
            addCriterion("acctauthentic not between", value1, value2, "acctauthentic");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startIsNull() {
            addCriterion("connectinfo_start is null");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startIsNotNull() {
            addCriterion("connectinfo_start is not null");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startEqualTo(String value) {
            addCriterion("connectinfo_start =", value, "connectinfo_start");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startNotEqualTo(String value) {
            addCriterion("connectinfo_start <>", value, "connectinfo_start");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startGreaterThan(String value) {
            addCriterion("connectinfo_start >", value, "connectinfo_start");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startGreaterThanOrEqualTo(String value) {
            addCriterion("connectinfo_start >=", value, "connectinfo_start");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startLessThan(String value) {
            addCriterion("connectinfo_start <", value, "connectinfo_start");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startLessThanOrEqualTo(String value) {
            addCriterion("connectinfo_start <=", value, "connectinfo_start");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startLike(String value) {
            addCriterion("connectinfo_start like", value, "connectinfo_start");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startNotLike(String value) {
            addCriterion("connectinfo_start not like", value, "connectinfo_start");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startIn(List<String> values) {
            addCriterion("connectinfo_start in", values, "connectinfo_start");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startNotIn(List<String> values) {
            addCriterion("connectinfo_start not in", values, "connectinfo_start");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startBetween(String value1, String value2) {
            addCriterion("connectinfo_start between", value1, value2, "connectinfo_start");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_startNotBetween(String value1, String value2) {
            addCriterion("connectinfo_start not between", value1, value2, "connectinfo_start");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopIsNull() {
            addCriterion("connectinfo_stop is null");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopIsNotNull() {
            addCriterion("connectinfo_stop is not null");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopEqualTo(String value) {
            addCriterion("connectinfo_stop =", value, "connectinfo_stop");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopNotEqualTo(String value) {
            addCriterion("connectinfo_stop <>", value, "connectinfo_stop");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopGreaterThan(String value) {
            addCriterion("connectinfo_stop >", value, "connectinfo_stop");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopGreaterThanOrEqualTo(String value) {
            addCriterion("connectinfo_stop >=", value, "connectinfo_stop");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopLessThan(String value) {
            addCriterion("connectinfo_stop <", value, "connectinfo_stop");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopLessThanOrEqualTo(String value) {
            addCriterion("connectinfo_stop <=", value, "connectinfo_stop");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopLike(String value) {
            addCriterion("connectinfo_stop like", value, "connectinfo_stop");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopNotLike(String value) {
            addCriterion("connectinfo_stop not like", value, "connectinfo_stop");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopIn(List<String> values) {
            addCriterion("connectinfo_stop in", values, "connectinfo_stop");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopNotIn(List<String> values) {
            addCriterion("connectinfo_stop not in", values, "connectinfo_stop");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopBetween(String value1, String value2) {
            addCriterion("connectinfo_stop between", value1, value2, "connectinfo_stop");
            return (Criteria) this;
        }

        public Criteria andConnectinfo_stopNotBetween(String value1, String value2) {
            addCriterion("connectinfo_stop not between", value1, value2, "connectinfo_stop");
            return (Criteria) this;
        }

        public Criteria andAcctinputoctetsIsNull() {
            addCriterion("acctinputoctets is null");
            return (Criteria) this;
        }

        public Criteria andAcctinputoctetsIsNotNull() {
            addCriterion("acctinputoctets is not null");
            return (Criteria) this;
        }

        public Criteria andAcctinputoctetsEqualTo(Long value) {
            addCriterion("acctinputoctets =", value, "acctinputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctinputoctetsNotEqualTo(Long value) {
            addCriterion("acctinputoctets <>", value, "acctinputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctinputoctetsGreaterThan(Long value) {
            addCriterion("acctinputoctets >", value, "acctinputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctinputoctetsGreaterThanOrEqualTo(Long value) {
            addCriterion("acctinputoctets >=", value, "acctinputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctinputoctetsLessThan(Long value) {
            addCriterion("acctinputoctets <", value, "acctinputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctinputoctetsLessThanOrEqualTo(Long value) {
            addCriterion("acctinputoctets <=", value, "acctinputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctinputoctetsIn(List<Long> values) {
            addCriterion("acctinputoctets in", values, "acctinputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctinputoctetsNotIn(List<Long> values) {
            addCriterion("acctinputoctets not in", values, "acctinputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctinputoctetsBetween(Long value1, Long value2) {
            addCriterion("acctinputoctets between", value1, value2, "acctinputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctinputoctetsNotBetween(Long value1, Long value2) {
            addCriterion("acctinputoctets not between", value1, value2, "acctinputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctoutputoctetsIsNull() {
            addCriterion("acctoutputoctets is null");
            return (Criteria) this;
        }

        public Criteria andAcctoutputoctetsIsNotNull() {
            addCriterion("acctoutputoctets is not null");
            return (Criteria) this;
        }

        public Criteria andAcctoutputoctetsEqualTo(Long value) {
            addCriterion("acctoutputoctets =", value, "acctoutputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctoutputoctetsNotEqualTo(Long value) {
            addCriterion("acctoutputoctets <>", value, "acctoutputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctoutputoctetsGreaterThan(Long value) {
            addCriterion("acctoutputoctets >", value, "acctoutputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctoutputoctetsGreaterThanOrEqualTo(Long value) {
            addCriterion("acctoutputoctets >=", value, "acctoutputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctoutputoctetsLessThan(Long value) {
            addCriterion("acctoutputoctets <", value, "acctoutputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctoutputoctetsLessThanOrEqualTo(Long value) {
            addCriterion("acctoutputoctets <=", value, "acctoutputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctoutputoctetsIn(List<Long> values) {
            addCriterion("acctoutputoctets in", values, "acctoutputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctoutputoctetsNotIn(List<Long> values) {
            addCriterion("acctoutputoctets not in", values, "acctoutputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctoutputoctetsBetween(Long value1, Long value2) {
            addCriterion("acctoutputoctets between", value1, value2, "acctoutputoctets");
            return (Criteria) this;
        }

        public Criteria andAcctoutputoctetsNotBetween(Long value1, Long value2) {
            addCriterion("acctoutputoctets not between", value1, value2, "acctoutputoctets");
            return (Criteria) this;
        }

        public Criteria andCalledstationidIsNull() {
            addCriterion("calledstationid is null");
            return (Criteria) this;
        }

        public Criteria andCalledstationidIsNotNull() {
            addCriterion("calledstationid is not null");
            return (Criteria) this;
        }

        public Criteria andCalledstationidEqualTo(String value) {
            addCriterion("calledstationid =", value, "calledstationid");
            return (Criteria) this;
        }

        public Criteria andCalledstationidNotEqualTo(String value) {
            addCriterion("calledstationid <>", value, "calledstationid");
            return (Criteria) this;
        }

        public Criteria andCalledstationidGreaterThan(String value) {
            addCriterion("calledstationid >", value, "calledstationid");
            return (Criteria) this;
        }

        public Criteria andCalledstationidGreaterThanOrEqualTo(String value) {
            addCriterion("calledstationid >=", value, "calledstationid");
            return (Criteria) this;
        }

        public Criteria andCalledstationidLessThan(String value) {
            addCriterion("calledstationid <", value, "calledstationid");
            return (Criteria) this;
        }

        public Criteria andCalledstationidLessThanOrEqualTo(String value) {
            addCriterion("calledstationid <=", value, "calledstationid");
            return (Criteria) this;
        }

        public Criteria andCalledstationidLike(String value) {
            addCriterion("calledstationid like", value, "calledstationid");
            return (Criteria) this;
        }

        public Criteria andCalledstationidNotLike(String value) {
            addCriterion("calledstationid not like", value, "calledstationid");
            return (Criteria) this;
        }

        public Criteria andCalledstationidIn(List<String> values) {
            addCriterion("calledstationid in", values, "calledstationid");
            return (Criteria) this;
        }

        public Criteria andCalledstationidNotIn(List<String> values) {
            addCriterion("calledstationid not in", values, "calledstationid");
            return (Criteria) this;
        }

        public Criteria andCalledstationidBetween(String value1, String value2) {
            addCriterion("calledstationid between", value1, value2, "calledstationid");
            return (Criteria) this;
        }

        public Criteria andCalledstationidNotBetween(String value1, String value2) {
            addCriterion("calledstationid not between", value1, value2, "calledstationid");
            return (Criteria) this;
        }

        public Criteria andCallingstationidIsNull() {
            addCriterion("callingstationid is null");
            return (Criteria) this;
        }

        public Criteria andCallingstationidIsNotNull() {
            addCriterion("callingstationid is not null");
            return (Criteria) this;
        }

        public Criteria andCallingstationidEqualTo(String value) {
            addCriterion("callingstationid =", value, "callingstationid");
            return (Criteria) this;
        }

        public Criteria andCallingstationidNotEqualTo(String value) {
            addCriterion("callingstationid <>", value, "callingstationid");
            return (Criteria) this;
        }

        public Criteria andCallingstationidGreaterThan(String value) {
            addCriterion("callingstationid >", value, "callingstationid");
            return (Criteria) this;
        }

        public Criteria andCallingstationidGreaterThanOrEqualTo(String value) {
            addCriterion("callingstationid >=", value, "callingstationid");
            return (Criteria) this;
        }

        public Criteria andCallingstationidLessThan(String value) {
            addCriterion("callingstationid <", value, "callingstationid");
            return (Criteria) this;
        }

        public Criteria andCallingstationidLessThanOrEqualTo(String value) {
            addCriterion("callingstationid <=", value, "callingstationid");
            return (Criteria) this;
        }

        public Criteria andCallingstationidLike(String value) {
            addCriterion("callingstationid like", value, "callingstationid");
            return (Criteria) this;
        }

        public Criteria andCallingstationidNotLike(String value) {
            addCriterion("callingstationid not like", value, "callingstationid");
            return (Criteria) this;
        }

        public Criteria andCallingstationidIn(List<String> values) {
            addCriterion("callingstationid in", values, "callingstationid");
            return (Criteria) this;
        }

        public Criteria andCallingstationidNotIn(List<String> values) {
            addCriterion("callingstationid not in", values, "callingstationid");
            return (Criteria) this;
        }

        public Criteria andCallingstationidBetween(String value1, String value2) {
            addCriterion("callingstationid between", value1, value2, "callingstationid");
            return (Criteria) this;
        }

        public Criteria andCallingstationidNotBetween(String value1, String value2) {
            addCriterion("callingstationid not between", value1, value2, "callingstationid");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseIsNull() {
            addCriterion("acctterminatecause is null");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseIsNotNull() {
            addCriterion("acctterminatecause is not null");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseEqualTo(String value) {
            addCriterion("acctterminatecause =", value, "acctterminatecause");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseNotEqualTo(String value) {
            addCriterion("acctterminatecause <>", value, "acctterminatecause");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseGreaterThan(String value) {
            addCriterion("acctterminatecause >", value, "acctterminatecause");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseGreaterThanOrEqualTo(String value) {
            addCriterion("acctterminatecause >=", value, "acctterminatecause");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseLessThan(String value) {
            addCriterion("acctterminatecause <", value, "acctterminatecause");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseLessThanOrEqualTo(String value) {
            addCriterion("acctterminatecause <=", value, "acctterminatecause");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseLike(String value) {
            addCriterion("acctterminatecause like", value, "acctterminatecause");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseNotLike(String value) {
            addCriterion("acctterminatecause not like", value, "acctterminatecause");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseIn(List<String> values) {
            addCriterion("acctterminatecause in", values, "acctterminatecause");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseNotIn(List<String> values) {
            addCriterion("acctterminatecause not in", values, "acctterminatecause");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseBetween(String value1, String value2) {
            addCriterion("acctterminatecause between", value1, value2, "acctterminatecause");
            return (Criteria) this;
        }

        public Criteria andAcctterminatecauseNotBetween(String value1, String value2) {
            addCriterion("acctterminatecause not between", value1, value2, "acctterminatecause");
            return (Criteria) this;
        }

        public Criteria andServicetypeIsNull() {
            addCriterion("servicetype is null");
            return (Criteria) this;
        }

        public Criteria andServicetypeIsNotNull() {
            addCriterion("servicetype is not null");
            return (Criteria) this;
        }

        public Criteria andServicetypeEqualTo(String value) {
            addCriterion("servicetype =", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeNotEqualTo(String value) {
            addCriterion("servicetype <>", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeGreaterThan(String value) {
            addCriterion("servicetype >", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeGreaterThanOrEqualTo(String value) {
            addCriterion("servicetype >=", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeLessThan(String value) {
            addCriterion("servicetype <", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeLessThanOrEqualTo(String value) {
            addCriterion("servicetype <=", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeLike(String value) {
            addCriterion("servicetype like", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeNotLike(String value) {
            addCriterion("servicetype not like", value, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeIn(List<String> values) {
            addCriterion("servicetype in", values, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeNotIn(List<String> values) {
            addCriterion("servicetype not in", values, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeBetween(String value1, String value2) {
            addCriterion("servicetype between", value1, value2, "servicetype");
            return (Criteria) this;
        }

        public Criteria andServicetypeNotBetween(String value1, String value2) {
            addCriterion("servicetype not between", value1, value2, "servicetype");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolIsNull() {
            addCriterion("framedprotocol is null");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolIsNotNull() {
            addCriterion("framedprotocol is not null");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolEqualTo(String value) {
            addCriterion("framedprotocol =", value, "framedprotocol");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolNotEqualTo(String value) {
            addCriterion("framedprotocol <>", value, "framedprotocol");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolGreaterThan(String value) {
            addCriterion("framedprotocol >", value, "framedprotocol");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolGreaterThanOrEqualTo(String value) {
            addCriterion("framedprotocol >=", value, "framedprotocol");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolLessThan(String value) {
            addCriterion("framedprotocol <", value, "framedprotocol");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolLessThanOrEqualTo(String value) {
            addCriterion("framedprotocol <=", value, "framedprotocol");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolLike(String value) {
            addCriterion("framedprotocol like", value, "framedprotocol");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolNotLike(String value) {
            addCriterion("framedprotocol not like", value, "framedprotocol");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolIn(List<String> values) {
            addCriterion("framedprotocol in", values, "framedprotocol");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolNotIn(List<String> values) {
            addCriterion("framedprotocol not in", values, "framedprotocol");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolBetween(String value1, String value2) {
            addCriterion("framedprotocol between", value1, value2, "framedprotocol");
            return (Criteria) this;
        }

        public Criteria andFramedprotocolNotBetween(String value1, String value2) {
            addCriterion("framedprotocol not between", value1, value2, "framedprotocol");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressIsNull() {
            addCriterion("framedipaddress is null");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressIsNotNull() {
            addCriterion("framedipaddress is not null");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressEqualTo(String value) {
            addCriterion("framedipaddress =", value, "framedipaddress");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressNotEqualTo(String value) {
            addCriterion("framedipaddress <>", value, "framedipaddress");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressGreaterThan(String value) {
            addCriterion("framedipaddress >", value, "framedipaddress");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressGreaterThanOrEqualTo(String value) {
            addCriterion("framedipaddress >=", value, "framedipaddress");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressLessThan(String value) {
            addCriterion("framedipaddress <", value, "framedipaddress");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressLessThanOrEqualTo(String value) {
            addCriterion("framedipaddress <=", value, "framedipaddress");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressLike(String value) {
            addCriterion("framedipaddress like", value, "framedipaddress");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressNotLike(String value) {
            addCriterion("framedipaddress not like", value, "framedipaddress");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressIn(List<String> values) {
            addCriterion("framedipaddress in", values, "framedipaddress");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressNotIn(List<String> values) {
            addCriterion("framedipaddress not in", values, "framedipaddress");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressBetween(String value1, String value2) {
            addCriterion("framedipaddress between", value1, value2, "framedipaddress");
            return (Criteria) this;
        }

        public Criteria andFramedipaddressNotBetween(String value1, String value2) {
            addCriterion("framedipaddress not between", value1, value2, "framedipaddress");
            return (Criteria) this;
        }

        public Criteria andAcctstartdelayIsNull() {
            addCriterion("acctstartdelay is null");
            return (Criteria) this;
        }

        public Criteria andAcctstartdelayIsNotNull() {
            addCriterion("acctstartdelay is not null");
            return (Criteria) this;
        }

        public Criteria andAcctstartdelayEqualTo(Integer value) {
            addCriterion("acctstartdelay =", value, "acctstartdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstartdelayNotEqualTo(Integer value) {
            addCriterion("acctstartdelay <>", value, "acctstartdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstartdelayGreaterThan(Integer value) {
            addCriterion("acctstartdelay >", value, "acctstartdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstartdelayGreaterThanOrEqualTo(Integer value) {
            addCriterion("acctstartdelay >=", value, "acctstartdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstartdelayLessThan(Integer value) {
            addCriterion("acctstartdelay <", value, "acctstartdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstartdelayLessThanOrEqualTo(Integer value) {
            addCriterion("acctstartdelay <=", value, "acctstartdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstartdelayIn(List<Integer> values) {
            addCriterion("acctstartdelay in", values, "acctstartdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstartdelayNotIn(List<Integer> values) {
            addCriterion("acctstartdelay not in", values, "acctstartdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstartdelayBetween(Integer value1, Integer value2) {
            addCriterion("acctstartdelay between", value1, value2, "acctstartdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstartdelayNotBetween(Integer value1, Integer value2) {
            addCriterion("acctstartdelay not between", value1, value2, "acctstartdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstopdelayIsNull() {
            addCriterion("acctstopdelay is null");
            return (Criteria) this;
        }

        public Criteria andAcctstopdelayIsNotNull() {
            addCriterion("acctstopdelay is not null");
            return (Criteria) this;
        }

        public Criteria andAcctstopdelayEqualTo(Integer value) {
            addCriterion("acctstopdelay =", value, "acctstopdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstopdelayNotEqualTo(Integer value) {
            addCriterion("acctstopdelay <>", value, "acctstopdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstopdelayGreaterThan(Integer value) {
            addCriterion("acctstopdelay >", value, "acctstopdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstopdelayGreaterThanOrEqualTo(Integer value) {
            addCriterion("acctstopdelay >=", value, "acctstopdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstopdelayLessThan(Integer value) {
            addCriterion("acctstopdelay <", value, "acctstopdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstopdelayLessThanOrEqualTo(Integer value) {
            addCriterion("acctstopdelay <=", value, "acctstopdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstopdelayIn(List<Integer> values) {
            addCriterion("acctstopdelay in", values, "acctstopdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstopdelayNotIn(List<Integer> values) {
            addCriterion("acctstopdelay not in", values, "acctstopdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstopdelayBetween(Integer value1, Integer value2) {
            addCriterion("acctstopdelay between", value1, value2, "acctstopdelay");
            return (Criteria) this;
        }

        public Criteria andAcctstopdelayNotBetween(Integer value1, Integer value2) {
            addCriterion("acctstopdelay not between", value1, value2, "acctstopdelay");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyIsNull() {
            addCriterion("xascendsessionsvrkey is null");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyIsNotNull() {
            addCriterion("xascendsessionsvrkey is not null");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyEqualTo(String value) {
            addCriterion("xascendsessionsvrkey =", value, "xascendsessionsvrkey");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyNotEqualTo(String value) {
            addCriterion("xascendsessionsvrkey <>", value, "xascendsessionsvrkey");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyGreaterThan(String value) {
            addCriterion("xascendsessionsvrkey >", value, "xascendsessionsvrkey");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyGreaterThanOrEqualTo(String value) {
            addCriterion("xascendsessionsvrkey >=", value, "xascendsessionsvrkey");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyLessThan(String value) {
            addCriterion("xascendsessionsvrkey <", value, "xascendsessionsvrkey");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyLessThanOrEqualTo(String value) {
            addCriterion("xascendsessionsvrkey <=", value, "xascendsessionsvrkey");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyLike(String value) {
            addCriterion("xascendsessionsvrkey like", value, "xascendsessionsvrkey");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyNotLike(String value) {
            addCriterion("xascendsessionsvrkey not like", value, "xascendsessionsvrkey");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyIn(List<String> values) {
            addCriterion("xascendsessionsvrkey in", values, "xascendsessionsvrkey");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyNotIn(List<String> values) {
            addCriterion("xascendsessionsvrkey not in", values, "xascendsessionsvrkey");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyBetween(String value1, String value2) {
            addCriterion("xascendsessionsvrkey between", value1, value2, "xascendsessionsvrkey");
            return (Criteria) this;
        }

        public Criteria andXascendsessionsvrkeyNotBetween(String value1, String value2) {
            addCriterion("xascendsessionsvrkey not between", value1, value2, "xascendsessionsvrkey");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table radacct
     *
     * @mbggenerated do_not_delete_during_merge Sun Apr 17 22:01:58 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table radacct
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}