package me.superkoh.evpn.domain.model;

public class RadUserGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column radusergroup.username
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column radusergroup.groupname
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column radusergroup.priority
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private Integer priority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column radusergroup.username
     *
     * @return the value of radusergroup.username
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column radusergroup.username
     *
     * @param username the value for radusergroup.username
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column radusergroup.groupname
     *
     * @return the value of radusergroup.groupname
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column radusergroup.groupname
     *
     * @param groupname the value for radusergroup.groupname
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column radusergroup.priority
     *
     * @return the value of radusergroup.priority
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column radusergroup.priority
     *
     * @param priority the value for radusergroup.priority
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
}