package me.superkoh.evpn.domain.model;

import java.util.Date;

public class UserBillInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.id
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.username
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.planName
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String planName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.hotspot_id
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private Integer hotspot_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.hotspotlocation
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String hotspotlocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.contactperson
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String contactperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.company
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.email
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.phone
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.address
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.city
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.state
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.country
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.zip
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.paymentmethod
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String paymentmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.cash
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String cash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.creditcardname
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String creditcardname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.creditcardnumber
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String creditcardnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.creditcardverification
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String creditcardverification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.creditcardtype
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String creditcardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.creditcardexp
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String creditcardexp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.notes
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String notes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.changeuserbillinfo
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String changeuserbillinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.lead
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String lead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.coupon
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String coupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.ordertaker
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String ordertaker;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.billstatus
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String billstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.lastbill
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private Date lastbill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.nextbill
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private Date nextbill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.nextinvoicedue
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private Integer nextinvoicedue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.billdue
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private Integer billdue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.postalinvoice
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String postalinvoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.faxinvoice
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String faxinvoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.emailinvoice
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String emailinvoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.batch_id
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private Integer batch_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.creationdate
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.creationby
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String creationby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.updatedate
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private Date updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userbillinfo.updateby
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    private String updateby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.id
     *
     * @return the value of userbillinfo.id
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.id
     *
     * @param id the value for userbillinfo.id
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.username
     *
     * @return the value of userbillinfo.username
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.username
     *
     * @param username the value for userbillinfo.username
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.planName
     *
     * @return the value of userbillinfo.planName
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getPlanName() {
        return planName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.planName
     *
     * @param planName the value for userbillinfo.planName
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setPlanName(String planName) {
        this.planName = planName == null ? null : planName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.hotspot_id
     *
     * @return the value of userbillinfo.hotspot_id
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Integer getHotspot_id() {
        return hotspot_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.hotspot_id
     *
     * @param hotspot_id the value for userbillinfo.hotspot_id
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setHotspot_id(Integer hotspot_id) {
        this.hotspot_id = hotspot_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.hotspotlocation
     *
     * @return the value of userbillinfo.hotspotlocation
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getHotspotlocation() {
        return hotspotlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.hotspotlocation
     *
     * @param hotspotlocation the value for userbillinfo.hotspotlocation
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setHotspotlocation(String hotspotlocation) {
        this.hotspotlocation = hotspotlocation == null ? null : hotspotlocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.contactperson
     *
     * @return the value of userbillinfo.contactperson
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getContactperson() {
        return contactperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.contactperson
     *
     * @param contactperson the value for userbillinfo.contactperson
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setContactperson(String contactperson) {
        this.contactperson = contactperson == null ? null : contactperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.company
     *
     * @return the value of userbillinfo.company
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.company
     *
     * @param company the value for userbillinfo.company
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.email
     *
     * @return the value of userbillinfo.email
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.email
     *
     * @param email the value for userbillinfo.email
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.phone
     *
     * @return the value of userbillinfo.phone
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.phone
     *
     * @param phone the value for userbillinfo.phone
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.address
     *
     * @return the value of userbillinfo.address
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.address
     *
     * @param address the value for userbillinfo.address
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.city
     *
     * @return the value of userbillinfo.city
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.city
     *
     * @param city the value for userbillinfo.city
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.state
     *
     * @return the value of userbillinfo.state
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.state
     *
     * @param state the value for userbillinfo.state
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.country
     *
     * @return the value of userbillinfo.country
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.country
     *
     * @param country the value for userbillinfo.country
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.zip
     *
     * @return the value of userbillinfo.zip
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.zip
     *
     * @param zip the value for userbillinfo.zip
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.paymentmethod
     *
     * @return the value of userbillinfo.paymentmethod
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getPaymentmethod() {
        return paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.paymentmethod
     *
     * @param paymentmethod the value for userbillinfo.paymentmethod
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setPaymentmethod(String paymentmethod) {
        this.paymentmethod = paymentmethod == null ? null : paymentmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.cash
     *
     * @return the value of userbillinfo.cash
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getCash() {
        return cash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.cash
     *
     * @param cash the value for userbillinfo.cash
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setCash(String cash) {
        this.cash = cash == null ? null : cash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.creditcardname
     *
     * @return the value of userbillinfo.creditcardname
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getCreditcardname() {
        return creditcardname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.creditcardname
     *
     * @param creditcardname the value for userbillinfo.creditcardname
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setCreditcardname(String creditcardname) {
        this.creditcardname = creditcardname == null ? null : creditcardname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.creditcardnumber
     *
     * @return the value of userbillinfo.creditcardnumber
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getCreditcardnumber() {
        return creditcardnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.creditcardnumber
     *
     * @param creditcardnumber the value for userbillinfo.creditcardnumber
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setCreditcardnumber(String creditcardnumber) {
        this.creditcardnumber = creditcardnumber == null ? null : creditcardnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.creditcardverification
     *
     * @return the value of userbillinfo.creditcardverification
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getCreditcardverification() {
        return creditcardverification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.creditcardverification
     *
     * @param creditcardverification the value for userbillinfo.creditcardverification
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setCreditcardverification(String creditcardverification) {
        this.creditcardverification = creditcardverification == null ? null : creditcardverification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.creditcardtype
     *
     * @return the value of userbillinfo.creditcardtype
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getCreditcardtype() {
        return creditcardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.creditcardtype
     *
     * @param creditcardtype the value for userbillinfo.creditcardtype
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setCreditcardtype(String creditcardtype) {
        this.creditcardtype = creditcardtype == null ? null : creditcardtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.creditcardexp
     *
     * @return the value of userbillinfo.creditcardexp
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getCreditcardexp() {
        return creditcardexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.creditcardexp
     *
     * @param creditcardexp the value for userbillinfo.creditcardexp
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setCreditcardexp(String creditcardexp) {
        this.creditcardexp = creditcardexp == null ? null : creditcardexp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.notes
     *
     * @return the value of userbillinfo.notes
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.notes
     *
     * @param notes the value for userbillinfo.notes
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.changeuserbillinfo
     *
     * @return the value of userbillinfo.changeuserbillinfo
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getChangeuserbillinfo() {
        return changeuserbillinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.changeuserbillinfo
     *
     * @param changeuserbillinfo the value for userbillinfo.changeuserbillinfo
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setChangeuserbillinfo(String changeuserbillinfo) {
        this.changeuserbillinfo = changeuserbillinfo == null ? null : changeuserbillinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.lead
     *
     * @return the value of userbillinfo.lead
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getLead() {
        return lead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.lead
     *
     * @param lead the value for userbillinfo.lead
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setLead(String lead) {
        this.lead = lead == null ? null : lead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.coupon
     *
     * @return the value of userbillinfo.coupon
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getCoupon() {
        return coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.coupon
     *
     * @param coupon the value for userbillinfo.coupon
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setCoupon(String coupon) {
        this.coupon = coupon == null ? null : coupon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.ordertaker
     *
     * @return the value of userbillinfo.ordertaker
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getOrdertaker() {
        return ordertaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.ordertaker
     *
     * @param ordertaker the value for userbillinfo.ordertaker
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setOrdertaker(String ordertaker) {
        this.ordertaker = ordertaker == null ? null : ordertaker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.billstatus
     *
     * @return the value of userbillinfo.billstatus
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getBillstatus() {
        return billstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.billstatus
     *
     * @param billstatus the value for userbillinfo.billstatus
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setBillstatus(String billstatus) {
        this.billstatus = billstatus == null ? null : billstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.lastbill
     *
     * @return the value of userbillinfo.lastbill
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Date getLastbill() {
        return lastbill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.lastbill
     *
     * @param lastbill the value for userbillinfo.lastbill
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setLastbill(Date lastbill) {
        this.lastbill = lastbill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.nextbill
     *
     * @return the value of userbillinfo.nextbill
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Date getNextbill() {
        return nextbill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.nextbill
     *
     * @param nextbill the value for userbillinfo.nextbill
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setNextbill(Date nextbill) {
        this.nextbill = nextbill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.nextinvoicedue
     *
     * @return the value of userbillinfo.nextinvoicedue
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Integer getNextinvoicedue() {
        return nextinvoicedue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.nextinvoicedue
     *
     * @param nextinvoicedue the value for userbillinfo.nextinvoicedue
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setNextinvoicedue(Integer nextinvoicedue) {
        this.nextinvoicedue = nextinvoicedue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.billdue
     *
     * @return the value of userbillinfo.billdue
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Integer getBilldue() {
        return billdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.billdue
     *
     * @param billdue the value for userbillinfo.billdue
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setBilldue(Integer billdue) {
        this.billdue = billdue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.postalinvoice
     *
     * @return the value of userbillinfo.postalinvoice
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getPostalinvoice() {
        return postalinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.postalinvoice
     *
     * @param postalinvoice the value for userbillinfo.postalinvoice
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setPostalinvoice(String postalinvoice) {
        this.postalinvoice = postalinvoice == null ? null : postalinvoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.faxinvoice
     *
     * @return the value of userbillinfo.faxinvoice
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getFaxinvoice() {
        return faxinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.faxinvoice
     *
     * @param faxinvoice the value for userbillinfo.faxinvoice
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setFaxinvoice(String faxinvoice) {
        this.faxinvoice = faxinvoice == null ? null : faxinvoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.emailinvoice
     *
     * @return the value of userbillinfo.emailinvoice
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getEmailinvoice() {
        return emailinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.emailinvoice
     *
     * @param emailinvoice the value for userbillinfo.emailinvoice
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setEmailinvoice(String emailinvoice) {
        this.emailinvoice = emailinvoice == null ? null : emailinvoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.batch_id
     *
     * @return the value of userbillinfo.batch_id
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Integer getBatch_id() {
        return batch_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.batch_id
     *
     * @param batch_id the value for userbillinfo.batch_id
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setBatch_id(Integer batch_id) {
        this.batch_id = batch_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.creationdate
     *
     * @return the value of userbillinfo.creationdate
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.creationdate
     *
     * @param creationdate the value for userbillinfo.creationdate
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.creationby
     *
     * @return the value of userbillinfo.creationby
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getCreationby() {
        return creationby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.creationby
     *
     * @param creationby the value for userbillinfo.creationby
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setCreationby(String creationby) {
        this.creationby = creationby == null ? null : creationby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.updatedate
     *
     * @return the value of userbillinfo.updatedate
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.updatedate
     *
     * @param updatedate the value for userbillinfo.updatedate
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userbillinfo.updateby
     *
     * @return the value of userbillinfo.updateby
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public String getUpdateby() {
        return updateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userbillinfo.updateby
     *
     * @param updateby the value for userbillinfo.updateby
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    public void setUpdateby(String updateby) {
        this.updateby = updateby == null ? null : updateby.trim();
    }
}