package me.superkoh.evpn.domain.mapper;

import java.util.List;
import me.superkoh.evpn.domain.model.EVpnInviteCode;
import me.superkoh.evpn.domain.model.EVpnInviteCodeExample;
import org.apache.ibatis.annotations.Param;

public interface EVpnInviteCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_invite_code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int countByExample(EVpnInviteCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_invite_code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int deleteByExample(EVpnInviteCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_invite_code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_invite_code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int insert(EVpnInviteCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_invite_code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int insertSelective(EVpnInviteCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_invite_code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    List<EVpnInviteCode> selectByExample(EVpnInviteCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_invite_code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    EVpnInviteCode selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_invite_code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByExampleSelective(@Param("record") EVpnInviteCode record, @Param("example") EVpnInviteCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_invite_code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByExample(@Param("record") EVpnInviteCode record, @Param("example") EVpnInviteCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_invite_code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByPrimaryKeySelective(EVpnInviteCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_invite_code
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByPrimaryKey(EVpnInviteCode record);
}