package me.superkoh.evpn.domain.mapper;

import java.util.List;
import me.superkoh.evpn.domain.model.EVpnUser;
import me.superkoh.evpn.domain.model.EVpnUserExample;
import org.apache.ibatis.annotations.Param;

public interface EVpnUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int countByExample(EVpnUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int deleteByExample(EVpnUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int insert(EVpnUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int insertSelective(EVpnUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    List<EVpnUser> selectByExample(EVpnUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    EVpnUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByExampleSelective(@Param("record") EVpnUser record, @Param("example") EVpnUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByExample(@Param("record") EVpnUser record, @Param("example") EVpnUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByPrimaryKeySelective(EVpnUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table evpn_user
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByPrimaryKey(EVpnUser record);
}