package me.superkoh.evpn.domain.mapper;

import java.util.List;
import me.superkoh.evpn.domain.model.Nas;
import me.superkoh.evpn.domain.model.NasExample;
import org.apache.ibatis.annotations.Param;

public interface NasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nas
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int countByExample(NasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nas
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int deleteByExample(NasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nas
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nas
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int insert(Nas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nas
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int insertSelective(Nas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nas
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    List<Nas> selectByExample(NasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nas
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    Nas selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nas
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") Nas record, @Param("example") NasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nas
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int updateByExample(@Param("record") Nas record, @Param("example") NasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nas
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int updateByPrimaryKeySelective(Nas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nas
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int updateByPrimaryKey(Nas record);
}