package me.superkoh.evpn.domain.mapper;

import java.util.List;
import me.superkoh.evpn.domain.model.RadAcct;
import me.superkoh.evpn.domain.model.RadAcctExample;
import org.apache.ibatis.annotations.Param;

public interface RadAcctMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int countByExample(RadAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int deleteByExample(RadAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int deleteByPrimaryKey(Long radacctid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int insert(RadAcct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int insertSelective(RadAcct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    List<RadAcct> selectByExample(RadAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    RadAcct selectByPrimaryKey(Long radacctid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByExampleSelective(@Param("record") RadAcct record, @Param("example") RadAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByExample(@Param("record") RadAcct record, @Param("example") RadAcctExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByPrimaryKeySelective(RadAcct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radacct
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByPrimaryKey(RadAcct record);
}