package me.superkoh.evpn.domain.mapper;

import java.util.List;
import me.superkoh.evpn.domain.model.RadCheck;
import me.superkoh.evpn.domain.model.RadCheckExample;
import org.apache.ibatis.annotations.Param;

public interface RadCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radcheck
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int countByExample(RadCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radcheck
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int deleteByExample(RadCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radcheck
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radcheck
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int insert(RadCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radcheck
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int insertSelective(RadCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radcheck
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    List<RadCheck> selectByExample(RadCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radcheck
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    RadCheck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radcheck
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") RadCheck record, @Param("example") RadCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radcheck
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int updateByExample(@Param("record") RadCheck record, @Param("example") RadCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radcheck
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int updateByPrimaryKeySelective(RadCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radcheck
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int updateByPrimaryKey(RadCheck record);
}