package me.superkoh.evpn.domain.mapper;

import java.util.List;
import me.superkoh.evpn.domain.model.RadUserGroup;
import me.superkoh.evpn.domain.model.RadUserGroupExample;
import org.apache.ibatis.annotations.Param;

public interface RadUserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radusergroup
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int countByExample(RadUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radusergroup
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int deleteByExample(RadUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radusergroup
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int insert(RadUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radusergroup
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int insertSelective(RadUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radusergroup
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    List<RadUserGroup> selectByExample(RadUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radusergroup
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") RadUserGroup record, @Param("example") RadUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table radusergroup
     *
     * @mbggenerated Sun Apr 17 22:01:58 CST 2016
     */
    int updateByExample(@Param("record") RadUserGroup record, @Param("example") RadUserGroupExample example);
}