package me.superkoh.evpn.domain.mapper;

import java.util.List;
import me.superkoh.evpn.domain.model.UserBillInfo;
import me.superkoh.evpn.domain.model.UserBillInfoExample;
import org.apache.ibatis.annotations.Param;

public interface UserBillInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbillinfo
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int countByExample(UserBillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbillinfo
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int deleteByExample(UserBillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbillinfo
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbillinfo
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int insert(UserBillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbillinfo
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int insertSelective(UserBillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbillinfo
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    List<UserBillInfo> selectByExample(UserBillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbillinfo
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    UserBillInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbillinfo
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserBillInfo record, @Param("example") UserBillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbillinfo
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByExample(@Param("record") UserBillInfo record, @Param("example") UserBillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbillinfo
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByPrimaryKeySelective(UserBillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userbillinfo
     *
     * @mbggenerated Thu Apr 21 22:44:30 CST 2016
     */
    int updateByPrimaryKey(UserBillInfo record);
}